### Registro de un usuario
POST http://localhost:6300/api/auth/register
Content-Type: application/json

{
    "name_user": "Jose Santana",
    "email_user": "joseasantana05@gmail.com",
    "password_user": "JSa06...",
    "username_user": "JoseS-Dev"
}

### Login de un usuario
POST http://localhost:6300/api/auth/login
Content-Type: application/json

{
    "email_user": "joseasantana05@gmail.com",
    "password_user": "JSa06..."
}

### Cerrar Sesión de un usuario
POST http://localhost:6300/api/auth/logout
Content-Type: application/json

{
    "email_user": "joseasantana05@gmail.com"
}

### Crear un luchador
POST http://localhost:6300/api/fighters/create
Content-Type: multipart/form-data; boundary=CustomBoundary

--CustomBoundary
Content-Disposition: form-data; name="name_fighter"

Michael Bisping
--CustomBoundary
Content-Disposition: form-data; name="nickname_fighter"

The Count
--CustomBoundary
Content-Disposition: form-data; name="age_fighter"

39
--CustomBoundary
Content-Disposition: form-data; name="height_fighter"

1.93
--CustomBoundary
Content-Disposition: form-data; name="weight_fighter"

93.0
--CustomBoundary
Content-Disposition: form-data; name="stance_fighter"

orthodox
--CustomBoundary
Content-Disposition: form-data; name="country_fighter"

England
--CustomBoundary
Content-Disposition: form-data; name="image_fighter"; filename="jon_jones.jpg"
Content-Type: image/jpeg

< ./uploads/michael_bisping.jpg
--CustomBoundary
Content-Disposition: form-data; name="team_id"

1
--CustomBoundary
Content-Disposition: form-data; name="category_id"

8
--CustomBoundary--

### Obtener todos los luchadores
GET http://localhost:6300/api/fighters/all

### Obtener un luchador por ID
GET http://localhost:6300/api/fighters/fighter/3

### Marcar o desmarcar un luchador como favorito
POST http://localhost:6300/api/fighters/favorite
Content-Type: application/json

{
    "fighter_id": 2,
    "user_id": 1,
    "is_favorite": true
}

### Obtener luchadores favoritos de un usuario
GET http://localhost:6300/api/fighters/favorites/1

### Bloquear o desbloquear un luchador (solo admin)
POST http://localhost:6300/api/fighters/block
Content-Type: application/json

{
    "id": 2,
    "is_blocked": false
}

### Obtener luchadores bloqueados (solo admin)
GET http://localhost:6300/api/fighters/blocked

### Actualizar un luchador
PATCH http://localhost:6300/api/fighters/update/2
Content-Type: multipart/form-data; boundary=CustomBoundary

--CustomBoundary
Content-Disposition: form-data; name="name_fighter"

George St-Pierre
--CustomBoundary
Content-Disposition: form-data; name="nickname_fighter"

Rush
--CustomBoundary
Content-Disposition: form-data; name="age_fighter"

37
--CustomBoundary
Content-Disposition: form-data; name="height_fighter"

1.78
--CustomBoundary
Content-Disposition: form-data; name="weight_fighter"

84.0
--CustomBoundary
Content-Disposition: form-data; name="stance_fighter"

orthodox
--CustomBoundary
Content-Disposition: form-data; name="country_fighter"

Canada
--CustomBoundary
Content-Disposition: form-data; name="image_fighter"; filename="jon_jones.jpg"
Content-Type: image/jpeg

< ./uploads/GSP.jpg
--CustomBoundary
Content-Disposition: form-data; name="team_id"

2
--CustomBoundary
Content-Disposition: form-data; name="category_id"

8
--CustomBoundary--

### Eliminar un luchador
DELETE http://localhost:6300/api/fighters/delete/2

### Crear las estadísticas de un luchador
POST http://localhost:6300/api/stadistics/create/3
Content-Type: application/json

{
    "streak_fighter": "28-3-0",
    "ranking_fighter": 1,
    "precission_strike_fighter": 55.3,
    "precission_takedown_fighter": 45.0,
    "date_debut_fighter": "2008-04-12",
    "last_fight_fighter": "2023-07-29",
    "knockout_win_fighter": 10,
    "submission_win_fighter": 5,
    "decision_win_fighter": 13,
    "title_wins_fighter": 11
}
### Actualizar las estadísticas de un luchador
PATCH http://localhost:6300/api/stadistics/update/3
Content-Type: application/json

{
    "ranking_fighter": 3,
    "precission_strike_fighter": 57.0,
    "last_fight_fighter": "2024-06-15",
    "knockout_win_fighter": 11
}

### Obtener las estadísticas de un luchador por ID
GET http://localhost:6300/api/stadistics/fighter/3

### Eliminar las estadísticas de un luchador por ID
DELETE http://localhost:6300/api/stadistics/delete/3

### Crear un evento
POST http://localhost:6300/api/events/create
Content-Type: multipart/form-data; boundary=CustomBoundary

--CustomBoundary
Content-Disposition: form-data; name="name_event"

UFC 300
--CustomBoundary
Content-Disposition: form-data; name="location_event"

Las Vegas, NV
--CustomBoundary
Content-Disposition: form-data; name="venue_event"

T-Mobile Arena
--CustomBoundary
Content-Disposition: form-data; name="date_event"

2024-11-02
--CustomBoundary
Content-Disposition: form-data; name="country_event"

USA
--CustomBoundary
Content-Disposition: form-data; name="image_event"; filename="ufc300.jpg"
Content-Type: image/jpeg

< ./uploads/ufc300.jpg
--CustomBoundary--

### Actualizar un evento
PATCH http://localhost:6300/api/events/event/update/1
Content-Type: multipart/form-data; boundary=CustomBoundary

--CustomBoundary
Content-Disposition: form-data; name="name_event"

UFC 301
--CustomBoundary
Content-Disposition: form-data; name="location_event"

Las Vegas, NV
--CustomBoundary
Content-Disposition: form-data; name="venue_event"

T-Mobile Arena
--CustomBoundary
Content-Disposition: form-data; name="date_event"

2024-11-02
--CustomBoundary
Content-Disposition: form-data; name="country_event"

USA
--CustomBoundary
Content-Disposition: form-data; name="image_event"; filename="ufc300.jpg"
Content-Type: image/jpeg

< ./uploads/ufc301.jpg
--CustomBoundary--

### Obtener todos los eventos
GET http://localhost:6300/api/events/all

### Obtener un evento por ID
GET http://localhost:6300/api/events/event/1

### Obtener un evento por el pais donde se realiza
GET http://localhost:6300/api/events/country/USA

### Eliminar un evento
DELETE http://localhost:6300/api/events/event/delete/2

### Crear una leyenda
POST http://localhost:6300/api/legends/create
Content-Type: multipart/form-data; boundary=CustomBoundary

--CustomBoundary
Content-Disposition: form-data; name="name_legend"

George St-Pierre
--CustomBoundary
Content-Disposition: form-data; name="nickname_legend"

Rush
--CustomBoundary
Content-Disposition: form-data; name="weight_legend"

37
--CustomBoundary
Content-Disposition: form-data; name="height_legend"

1.78
--CustomBoundary
Content-Disposition: form-data; name="stance_legend"

orthodox
--CustomBoundary
Content-Disposition: form-data; name="country_legend"

Canada
--CustomBoundary
Content-Disposition: form-data; name="streak_legend"

28-3-0
--CustomBoundary
Content-Disposition: form-data; name="image_legend"; filename="GSP.jpg"
Content-Type: image/jpeg

< ./uploads/GSP.jpg
--CustomBoundary
Content-Disposition: form-data; name="description_legend"

Considered one of the greatest mixed martial artists of all time, George St-Pierre is a former UFC Welterweight Champion known for his well-rounded skills, strategic fighting style, and sportsmanship both inside and outside the octagon.
--CustomBoundary
Content-Disposition: form-data; name="title_win_legend"

11
--CustomBoundary
Content-Disposition: form-data; name="trophys_legend"

13
--CustomBoundary
Content-Disposition: form-data; name="date_debut_legend"

2004-06-05
--CustomBoundary
Content-Disposition: form-data; name="date_retirement_legend"

2019-11-26
--CustomBoundary
Content-Disposition: form-data; name="period_active_legend"

2004-2019
--CustomBoundary--

### Marcar o desmarcar una leyenda como favorita para un usuario
POST http://localhost:6300/api/legends/favorite
Content-Type: application/json

{
    "legend_id": 2,
    "user_id": 1,
    "is_favorite": false
}

### Crear una leyenda
PATCH http://localhost:6300/api/legends/update/2
Content-Type: multipart/form-data; boundary=CustomBoundary

--CustomBoundary
Content-Disposition: form-data; name="name_legend"

George St-Pierre
--CustomBoundary
Content-Disposition: form-data; name="nickname_legend"

Rush
--CustomBoundary
Content-Disposition: form-data; name="weight_legend"

39
--CustomBoundary
Content-Disposition: form-data; name="height_legend"

1.78
--CustomBoundary
Content-Disposition: form-data; name="stance_legend"

orthodox
--CustomBoundary
Content-Disposition: form-data; name="country_legend"

Canada
--CustomBoundary
Content-Disposition: form-data; name="streak_legend"

31-3-0
--CustomBoundary
Content-Disposition: form-data; name="image_legend"; filename="GSP.jpg"
Content-Type: image/jpeg

< ./uploads/GSP.jpg
--CustomBoundary
Content-Disposition: form-data; name="description_legend"

Considered one of the greatest mixed martial artists of all time, George St-Pierre is a former UFC Welterweight Champion known for his well-rounded skills, strategic fighting style, and sportsmanship both inside and outside the octagon.
--CustomBoundary
Content-Disposition: form-data; name="title_win_legend"

11
--CustomBoundary
Content-Disposition: form-data; name="trophys_legend"

13
--CustomBoundary
Content-Disposition: form-data; name="date_debut_legend"

2004-06-05
--CustomBoundary
Content-Disposition: form-data; name="date_retirement_legend"

2019-11-26
--CustomBoundary
Content-Disposition: form-data; name="period_active_legend"

2004-2019
--CustomBoundary--

### Obtener todas las leyendas
GET http://localhost:6300/api/legends/all

### Obtener una leyenda por ID
GET http://localhost:6300/api/legends/legend/2

### Obtener leyendas favoritas de un usuario
GET http://localhost:6300/api/legends/favorites/1

### Eliminar una leyenda
DELETE http://localhost:6300/api/legends/delete/2

### Crear una noticia
POST http://localhost:6300/api/notices/create
Content-Type: multipart/form-data; boundary=CustomBoundary

--CustomBoundary
Content-Disposition: form-data; name="title_notice"

UFC 301 Set to Feature Historic Matchup
--CustomBoundary
Content-Disposition: form-data; name="content_notice"

The UFC is gearing up for a monumental event with UFC 301, scheduled to take place on November 2, 2024, at the T-Mobile Arena in Las Vegas, NV. This event promises to deliver an unforgettable night of fights, including a historic matchup that has fans buzzing with excitement.
--CustomBoundary
Content-Disposition: form-data; name="image_notice"; filename="UFC300.jpg"
Content-Type: image/jpeg

< ./https://th.bing.com/th/id/R.78129609b4b9e898298b9167347784e8?rik=GHHr64B4OkQ5ng&pid=ImgRaw&r=0
--CustomBoundary
Content-Disposition: form-data; name="video_notice"; filename="UFC300.mp4"
Content-Type: video/mp4

< ./uploads/UFC300.mp4
--CustomBoundary--

### Actualizar una noticia
PATCH http://localhost:6300/api/notices/update/1
Content-Type: multipart/form-data; boundary=CustomBoundary

--CustomBoundary
Content-Disposition: form-data; name="title_notice"

UFC 300 Set to Feature Historic Matchup
--CustomBoundary
Content-Disposition: form-data; name="content_notice"

The UFC is gearing up for a monumental event with UFC 300, scheduled to take place on November 2, 2024, at the T-Mobile Arena in Las Vegas, NV. This event promises to deliver an unforgettable night of fights, including a historic matchup that has fans buzzing with excitement.
--CustomBoundary
Content-Disposition: form-data; name="image_notice"; filename="UFC300.jpg"
Content-Type: image/jpeg

< ./uploads/UFC301.jpg
--CustomBoundary
Content-Disposition: form-data; name="video_notice"; filename="UFC300.mp4"
Content-Type: video/mp4

< ./uploads/UFC301.mp4
--CustomBoundary--

### Obtener todas las noticias
GET http://localhost:6300/api/notices/all

### Obtener una noticia por ID
GET http://localhost:6300/api/notices/notice/1

### Eliminar una noticia
DELETE http://localhost:6300/api/notices/delete/1

### Crear una pelea
POST http://localhost:6300/api/fights/create
Content-Type: application/json

{
    "event_id": 1,
    "fighter_red_id": 3,
    "fighter_blue_id": 4,
    "fight_order": 1,
    "is_title_fight": false,
    "is_main_event": false,
    "is_co_main_event": false,
    "weight_fight": "light heavyweight",
    "winner_fighter": "no contest"
}

### Actualizar una pelea
PATCH http://localhost:6300/api/fights/update/4
Content-Type: application/json

{
    "event_id": 1,
    "fighter_red_id": 3,
    "fighter_blue_id": 4,
    "fight_order": 1,
    "is_title_fight": true,
    "is_main_event": false,
    "is_co_main_event": false,
    "weight_fight": "light heavyweight",
    "winner_fighter": "blue"
}

### Obtener todas las peleas de un evento
GET http://localhost:6300/api/fights/event/1

### Obtener todas las peleas
GET http://localhost:6300/api/fights/all

### Obtener una pelea por ID
GET http://localhost:6300/api/fights/fight/4

### Eliminar una pelea
DELETE http://localhost:6300/api/fights/delete/4



